#SingleInstance Force
#Persistent
; =====================================================================
; Auto-generated by AHK Manager - 2025-11-12 20:25:49
; =====================================================================

#IfWinNotActive ahk_exe ONCE_HUMAN.exe
#IfWinNotActive ahk_exe DeltaForceclient-Win64-Shipping.exe
#IfWinNotActive ahk_exe df_garena_laucher.exe
#IfWinNotActive ahk_exe DeltaForce.exe
if not A_IsAdmin
{
   Run *RunAs "%A_ScriptFullPath%"  ; Bắt buộc chạy lại bằng quyền Admin
   ExitApp
}

; CÁC PHÍM TẮT & HOTSTRING SẼ BỊ VÔ HIỆU HÓA KHI DÙNG LDPLAYER
::xx::
Sendinput Pé đến gặp a trực tiếp ok hết rồi a thanh toán cho pé tại phòng phục vụ a nha
sleep 100
return

::ww::
SendMode Input
Send, Hi, Where are you from?
sleep 100
return

::dd::
Sendinput Do you want massage?
sleep 100
return

::ss::
Sendinput Meet not same or don't like you can cancel and don't need to pay anything
sleep 100
return

::qq::
SendMode Input
Send, We can meet first for you see me direct before deal, if meet and don't like you can reject and don't need to pay anything
sleep 100
return

::nn::
SendMode Input
Send, VietNam, Nice to meet you
sleep 100
return

::ii::
SendMode Input
Send, Send me address if you need, I can come to you
sleep 100
return

::,,::
SendMode Input
Send, Please choose a girl and she can come to your hotel or apartment
sleep 100
return

::mm::
SendMode Input
Send, My photos
sleep 100
return

::cc::
SendMode Input
Send, Can you take shot a photo of your key room and send it to me?
sleep 100
return

::ll::
SendMode Input
Send, Text me know when you need, I will come to you
sleep 100
return

::bb::
Sendinput Dịch vụ bao gồm mát xa body nude thư giãn, tắm chung và làm tình với pé ạ
sleep 100
return

::vv::
Sendinput Nào a cần a nói em nha, E đến tận nơi qua a
sleep 100
return

::ee::
Sendinput Hi A. A ở đâu vậy?
sleep 100
return

::oo::
Sendinput 1,5 milion for hour, 3,5 milion for overnight, Mαssαgє with sєx
sleep 100
return

::tt::
Sendinput E có dịch vụ mát xa làm tình giá 1tr5 1 giờ, qua đêm là 3tr5
sleep 100
return

::t1::
Sendinput A cần thì chọn 1 pé, pé đến tận nơi qua nha
sleep 100
return

::o3::
Sendinput 1.3 milions vnd for hour and 3 milions for overnight. Massage and Make love
sleep 100
return

::rr::
Sendinput Em nhận đi khách giá 1tr5 1 giờ, qua đêm là 3tr5, A cần nói em nha
sleep 100
return

::hh::
Sendinput Ảnh của em a xem nhé
sleep 100
return

::kk::
Sendinput Dạ a cần thì lấy phòng ks nào cũng đc rồi pé đến nha
sleep 100
return

::gg::
Sendinput Gặp không giống hay a ko thích a có quyền từ chối và ko cần trả tiền pé gì hết. A yên tâm nhé
sleep 100
return

::pp::
Sendinput A cần thì chọn một pé, pé sẽ đến tận nơi a nha
sleep 100
return

::jj::
Sendinput Phiền a chụp giúp thẻ phòng gửi qua em để pé xác nhận qua a nha
sleep 100
return

^2::
Sendinput https://github.com/Sxcution/Mon
sleep 100
return

^3::
Sendinput https://github.com/monsxcution/STool_v2
sleep 100
return

^5::
Sendinput timquanhday
sleep 100
return


!g::
Sendinput Dạ giá e đã bao gồm tất cả rồi không thêm gì a nha, a thấy pé phục vụ a tốt a có thể cho thêm hoặc ko tùy a nha
sleep 100
return

#IfWinActive